"""Read-only HTML projection; no workflow state or third-party dependencies."""
import hashlib
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

OUTPUT = 'workbench/development-dashboard/index.html'

MARKER = '<!-- Generated by HOTL dashboard. Do not edit. -->'


def render(store, state):
    def esc(value):
        return html.escape(str(value), quote=True)

    def local(relative):
        if not isinstance(relative, str) or not relative or '\\' in relative or ':' in relative:
            raise ValueError('Expected project-relative file path')
        path = Path(relative)
        target = store.root / path
        if path.is_absolute() or '..' in path.parts or any((store.root / Path(*path.parts[:i])).is_symlink() for i in range(1, len(path.parts) + 1)):
            raise ValueError('Unsafe dashboard path: ' + relative)
        return target

    def link(relative, label=None):
        path = local(relative)
        if not path.is_file():
            return '<span class="warn">未取得 / リンク切れ: ' + esc(label or relative) + '</span>'
        return '<a href="../../' + quote(relative, safe='/') + '">' + esc(label or relative) + '</a>'

    def textfile(relative):
        path = local(relative)
        return path.read_text() if path.is_file() else ''

    def stamp(relative):
        path = local(relative)
        return datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat(timespec='seconds') if path.is_file() else '未記録'

    config_text = textfile('docs/dashboard.json')
    config = json.loads(config_text) if config_text else {}
    if not isinstance(config, dict):
        raise ValueError('dashboard.json requires object')
    if set(config) - {'title', 'sections', 'ui_catalog'}:
        raise ValueError('Unknown dashboard configuration key')
    title = config.get('title', state['project'])
    if not isinstance(title, str) or not title.strip():
        raise ValueError('title requires nonempty string')
    sections = config.get('sections', ['checks', 'progress', 'tasks', 'ui'])
    if not isinstance(sections, list) or len(sections) != 4 or set(sections) != {'checks', 'progress', 'tasks', 'ui'}:
        raise ValueError('sections must list checks, progress, tasks, ui exactly once')
    catalog_path = config.get('ui_catalog', 'docs/ui-catalog.json')
    local(catalog_path)
    task_text = textfile('docs/tasks.md')
    resume_match = re.search(r'^## 再開[^\n]*\n(.*?)(?=^## |\Z)', task_text, re.M | re.S)
    resume = resume_match[1] if resume_match else '現在・次の順番・待ち/保留は未記録。tasks.md の再開欄を更新してください。'
    rows = store.tasks() if task_text else []
    task_map = {ident: (mark, title) for mark, ident, title in rows}
    labels = {' ': '未着手', '>': '進行中', '-': '保留', 'x': '完了（検証合格とは別）'}
    out = ['<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
           '<title>開発ダッシュボード</title>', MARKER,
           '<style>body{font:16px/1.7 system-ui;margin:auto;padding:24px;max-width:1100px;background:#f3f5fa;color:#192333}section,article{background:white;padding:20px;margin:16px 0;border:1px solid #c8d0df;border-radius:12px}h1,h2,h3{line-height:1.3}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}a{color:#164ab6}img,video{max-width:100%;max-height:440px}.warn{color:#a12817;font-weight:bold}li{margin:8px 0}small{color:#48566a}</style>',
           '<h1>' + esc(title) + ' · 開発ダッシュボード</h1>',
           '<section id="checks"><h2>あなたの確認が必要</h2>']
    active = [q for q in store.questions(state) if q['status'] == 'open']
    for q in active:
        out += ['<article><h3>' + esc(q['id'] + ' ' + q['title']) + '</h3><p>' + esc(q['reason']) + '</p><p>' + esc(q['recommendation']) + '</p><p>選択肢: ' + esc(' / '.join(q['options'])) + '</p><p>' + ('関連作業を保留' if q['blocking'] else '他の作業は続行可') + (' · <strong class="warn">対象変更済み・再提示が必要</strong>' if q['stale'] else '') + '</p><p>関連: ' + esc(', '.join(q['related'])) + '</p><p>' + ' · '.join(link(p) for p in q['targets']) + '</p></article>']
    if not active:
        out += ['<p>登録された確認待ちはありません。</p>']
    out += ['<p>回答はチャットで項目IDとともに伝えてください。画像の掲載だけでは承認・合格になりません。</p></section>',
            '<section id="progress"><h2>現在 / 次の順番 / 待ち・保留</h2><small>tasks.md 更新: ' + stamp('docs/tasks.md') + '</small><pre>' + esc(resume.strip()) + '</pre></section>',
            '<section id="tasks"><h2>タスク一覧</h2><ul>']
    out += ['<li>' + esc(ident + ' · ' + labels[mark] + ' · ' + title) + '</li>' for mark, ident, title in rows]
    out += ['</ul></section><section id="ui"><h2>UI一覧</h2><small>索引更新: ' + stamp(catalog_path) + '</small>']
    catalog_text = textfile(catalog_path)
    catalog = json.loads(catalog_text) if catalog_text else {'screens': []}
    if not isinstance(catalog, dict) or not isinstance(catalog.get('screens'), list):
        raise ValueError('ui-catalog.json requires screens array')
    if not catalog['screens']:
        out += ['<p>UI未登録。UIのないプロジェクトでは画像・動画は不要です。UIがある場合は画面単位で索引を登録してください。</p>']
    for screen in catalog['screens']:
        if not isinstance(screen, dict) or not isinstance(screen.get('name'), str):
            raise ValueError('Each screen requires name')
        out += ['<article><h3>' + esc(screen['name']) + '</h3>']
        for field, label in [('decision', '候補 / 採用の根拠'), ('integration', '本編接続のタスク'), ('verification', 'テスト / 目視 / 実機検証の記録')]:
            refs = screen.get(field, [])
            if not isinstance(refs, list):
                raise ValueError(field + ' requires array')
            out += ['<p>' + label + ': ' + (' · '.join(esc(ref + ' · ' + labels[task_map[ref][0]] + ' · ' + task_map[ref][1]) if ref in task_map else link(ref) for ref in refs) if refs else '未記録') + '</p>']
        media = screen.get('media', [])
        if not isinstance(media, list):
            raise ValueError('media requires array')
        if not media:
            out += ['<p class="warn">現在の画像・動画は未取得</p>']
        for item in media:
            if not isinstance(item, dict):
                raise ValueError('media entry requires object')
            path = local(item.get('path'))
            targets = item.get('targets', {})
            if not isinstance(targets, dict):
                raise ValueError('targets requires path/hash object')
            fresh = bool(targets) and all(local(p).is_file() and hashlib.sha256(local(p).read_bytes()).hexdigest() == sha for p, sha in targets.items())
            out += ['<p>撮影: ' + esc(item.get('captured_at', '未記録')) + ' · ' + ('登録対象のハッシュ一致（実機検証の代用ではありません）' if fresh else '<strong class="warn">現在版との一致未確認 / 古い資料</strong>') + '</p>', '<p>' + link(item['path']) + '</p>']
            ext = path.suffix.lower()
            url = '../../' + quote(item['path'], safe='/')
            if path.is_file() and ext in {'.png', '.jpg', '.jpeg', '.webp', '.gif'}:
                out += ['<img loading="lazy" src="' + url + '" alt="' + esc(screen['name']) + '">']
            elif path.is_file() and ext in {'.mp4', '.webm', '.mov'}:
                out += ['<video controls preload="metadata" src="' + url + '"></video>']
        out += ['</article>']
    out += ['</section><p>検証の有効性は check / trace と対象差分で確認してください。タスク完了、採用、接続、検証合格は別です。</p></html>']
    metadata = [
           '<p>保存時点の表示です。ライブ監視ではありません。変更後は sync で再生成してください。</p>',
           '<p>状態更新: ' + esc(state['updated_at']) + ' / revision ' + str(state['revision']) + ' / フェーズ: ' + esc(state['phase']) +
           ' / ' + ('<strong class="warn">停止中</strong>' if state['paused'] else '停止指示なし（実行中の証拠ではありません）') + '</p>',
           '<nav>' + ' · '.join(link('docs/' + p, label) for p, label in [('tasks.md', 'タスク正本'), ('handoff.md', '引き継ぎ入口'), ('user-checks.md', '確認履歴'), ('hotl.state.json', '状態・検証記録')]) + '</nav>',
    ]
    page = '\n'.join(out)
    blocks = dict(re.findall(r'<section id="(checks|progress|tasks|ui)">(.*?)</section>', page, re.S))
    prefix = page.split('<section id="checks">', 1)[0]
    suffix = page.rsplit('</section>', 1)[1]
    ordered = ['<section id="' + name + '">' + blocks[name] + '</section>' for name in sections]
    ordered.insert(1, '\n'.join(metadata))
    out = [prefix] + ordered + [suffix]
    # Content-derived freshness also detects edits to media targets without state writes.
    return ('\n'.join(out) + '\n').encode()
